### ISSUE TITLE
Package is incompatable with GHDL and Sublime Linter 4

### ISSUE THREAD

**Issue by ringof** [BrunoJJE/SublimeLinter-contrib-ghdl#4]
Please review both outstanding pull requests #2 and #3  - I have had to implement the same to make this package function, see https://github.com/ringof/SublimeLinter-contrib-ghdl

Alternatively, if you are no longer interested in maintaining this, might you give permission for allowing this code to continue under somebody else's efforts to be the official Sublime Linter GHDL package.

Thanks!

**Comment by BrunoJJE** [comment]
Hi. I am not using sublimetext anymore. Anybody interested to maintain a GHDL linter is welcome. If I need to take down this repo or do anything else, let me know.

**Comment by ringof** [comment]
It doesn't look like you need to do anything. From the new maintainer, it should be as simple as a PR on the SL package_control_channel repo, changing the link from yours to another one, and referencing this discussion to show the stated intent. I will update my fork of this repo to SublimeLinter's current standards and do the PR as suggested.

**Comment by ringof** [comment]
Updates and PRs done as stated, and Package Control now points to https://github.com/ringof/SublimeLinter-contrib-ghdl 

Thanks!
